name: 'Setup YQ'
description: 'Install YQ and add it to the PATH'
author: 'ibiqlik'

inputs:
  yq_version:
    description: 'The YQ version to install'
    required: false
    default: '3.3.2'

runs:
  using: 'composite'
  steps:
    - id: setup_yq
      run: ${{ github.action_path }}/main.sh
      shell: bash
      env:
        INPUT_YQ_VERSION: ${{ inputs.yq_version }}
