name: 'Check deployment'
description: 'GitHub Action for checking if pods and containers are up and running'
author: 'abuokoene'

inputs:
  namespace:
    description: 'The namespace to run action in'
    required: false
    default: 'default'

runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/main.sh
      shell: bash
      env:
        INPUT_NAMESPACE: ${{ inputs.namespace }}
