name: 'Make GitHub dispatch call'
description: 'Used to trigger release processes'
author: 'ibiqlik'

runs:
  using: 'composite'
  steps:
    - id: releaser-dispatch
      run: ${{ github.action_path }}/main.sh
      shell: bash
