version: "3.4"
services:
  otelcol:
    build:
      context: .
      dockerfile: Dockerfile.jaeger
    command: ["--config=/etc/otel-collector-config.yml", "--log-level=DEBUG"]
    ports:
      - "55680:55680"
      - "55681:55681"
    depends_on:
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp # UDP - thrift/compact
      - 6832:6832/udp # UDP - thrift/binary
      - 16686:16686 # HTTP - UI * API (/api/*)
      - 16687:16687 # HTTP - health (/) and metrics (/metrics)
      - 14268:14268 # HTTP - thift/binary
      - 14250:14250 # gRPC - from
