name: 'Helm test, package, push to Helm OCI registry'
description: 'GitHub Action for packaging, testing helm charts and publishing to Helm OCI registry'
author: 'ibiqlik'

inputs:
  action:
    required: false
    description: 'Options: package, test, publish, package_and_test'

runs:
  using: 'composite'
  steps:
    - id: helm-tools
      run: ${{ github.action_path }}/main.sh
      shell: bash
      env:
        INPUT_ACTION: ${{ inputs.action }}

branding:
  color: blue
  icon: check-square
